/*
    콘서트 예약 서비스 DDL
        - 회원 USER
        - 콘서트 CONCERT
        - 콘서트좌석 CONCERT_SEAT
        - 예약 RESERVATION
        - 예약상세 RESERVATION_ITEM
        - 결제 PAYMENT
        - 대기열 WAITING
*/

CREATE TABLE USER (
    USER_ID BIGINT AUTO_INCREMENT COMMENT '회원 ID',
    USER_NAME VARCHAR(50) NOT NULL COMMENT '회원명',
    POINT INT DEFAULT 0 COMMENT '포인트',
    CREATED_AT DATETIME DEFAULT NOW() COMMENT '생성일',
    UPDATED_AT DATETIME NULL COMMENT '수정일',
    DELETED_AT DATETIME NULL COMMENT '삭제일',
    PRIMARY KEY (USER_ID)
) COMMENT '회원';

CREATE TABLE POINT (
    POINT_ID BIGINT AUTO_INCREMENT COMMENT '포인트 ID',
    USER_ID BIGINT NOT NULL COMMENT '회원 ID',
    POINT INT DEFAULT 0 COMMENT '포인트',
    CREATED_AT DATETIME DEFAULT NOW() COMMENT '생성일',
    UPDATED_AT DATETIME NULL COMMENT '수정일',
    DELETED_AT DATETIME NULL COMMENT '삭제일',
    PRIMARY KEY (POINT_ID)
) COMMENT '포인트';

CREATE TABLE POINT_HISTORY (
    HISTORY_ID BIGINT AUTO_INCREMENT COMMENT '포인트내역 ID',
    POINT_ID BIGINT NOT NULL COMMENT '포인트 ID',
    TYPE VARCHAR(10) NOT NULL COMMENT '유형', -- CHARGE, USE
    AMOUNT INT NOT NULL COMMENT '금액',
    CREATED_AT DATETIME DEFAULT NOW() COMMENT '생성일',
    UPDATED_AT DATETIME NULL COMMENT '수정일',
    DELETED_AT DATETIME NULL COMMENT '삭제일',
    PRIMARY KEY (HISTORY_ID)
) COMMENT '포인트내역';


CREATE TABLE CONCERT (
    CONCERT_ID BIGINT AUTO_INCREMENT COMMENT '콘서트 ID',
    TITLE VARCHAR(100) NOT NULL COMMENT '제목',
    DESCRIPTION TEXT COMMENT '설명',
    CONCERT_START_AT DATETIME COMMENT '콘서트시작일',
    CONCERT_END_AT DATETIME COMMENT '콘서트종료일',
    RESERVATION_START_AT DATETIME COMMENT '예약시작일',
    RESERVATION_END_AT DATETIME COMMENT '예약종료일',
    CREATED_AT DATETIME DEFAULT NOW() COMMENT '생성일',
    UPDATED_AT DATETIME NULL COMMENT '수정일',
    DELETED_AT DATETIME NULL COMMENT '삭제일',
    PRIMARY KEY (CONCERT_ID)
) COMMENT '콘서트';

CREATE TABLE CONCERT_SEAT (
    SEAT_ID BIGINT AUTO_INCREMENT COMMENT '콘서트좌석 ID',
    CONCERT_ID BIGINT NOT NULL COMMENT '콘서트 ID',
    SEAT_NUM INT NOT NULL COMMENT '좌석번호',  -- 1-50
    STATUS VARCHAR(10) DEFAULT 'AVAILABLE' COMMENT '좌석상태', -- AVAILABLE, RESERVED, CONFIRMED
    RESERVED_AT DATETIME DEFAULT NOW() COMMENT '예약일',
    CREATED_AT DATETIME DEFAULT NOW() COMMENT '생성일',
    UPDATED_AT DATETIME NULL COMMENT '수정일',
    DELETED_AT DATETIME NULL COMMENT '삭제일',
    PRIMARY KEY (SEAT_ID)
) COMMENT '콘서트좌석';


CREATE TABLE RESERVATION (
    RESERVATION_ID BIGINT AUTO_INCREMENT COMMENT '예약 ID',
    USER_ID BIGINT NOT NULL COMMENT '회원 ID',
    CONCERT_TITLE VARCHAR(100) COMMENT '콘서트명',
    CONCERT_START_AT DATETIME COMMENT '콘서트시작일',
    CONCERT_END_AT DATETIME COMMENT '콘서트종료일',
    STATUS VARCHAR(10) DEFAULT 'SUCCESS' COMMENT '예약상태', -- SUCCESS, CANCELED
    CREATED_AT DATETIME DEFAULT NOW() COMMENT '생성일',
    UPDATED_AT DATETIME NULL COMMENT '수정일',
    DELETED_AT DATETIME NULL COMMENT '삭제일',
    PRIMARY KEY (RESERVATION_ID)
) COMMENT '예약';

CREATE TABLE RESERVATION_ITEM (
    ITEM_ID BIGINT AUTO_INCREMENT COMMENT '예약상세 ID',
    RESERVATION_ID BIGINT NOT NULL COMMENT '예약 ID',
    SEAT_ID BIGINT NOT NULL COMMENT '콘서트좌석 ID',
    CREATED_AT DATETIME DEFAULT NOW() COMMENT '생성일',
    UPDATED_AT DATETIME NULL COMMENT '수정일',
    DELETED_AT DATETIME NULL COMMENT '삭제일',
    PRIMARY KEY (ITEM_ID)
) COMMENT '예약상세';

CREATE TABLE PAYMENT (
    PAYMENT_ID BIGINT AUTO_INCREMENT COMMENT '결제 ID',
    RESERVATION_ID BIGINT NOT NULL COMMENT '예약 ID',
    USER_ID BIGINT NOT NULL COMMENT '회원 ID',
    PAYMENT_AMOUNT INT NOT NULL COMMENT '결제금액',
    STATUS VARCHAR(10) DEFAULT 'SUCCESS' COMMENT '결제상태', -- SUCCESS, CANCELED, FAIL
    CREATED_AT DATETIME DEFAULT NOW() COMMENT '생성일',
    UPDATED_AT DATETIME NULL COMMENT '수정일',
    DELETED_AT DATETIME NULL COMMENT '삭제일',
    PRIMARY KEY (PAYMENT_ID)
) COMMENT '결제';


CREATE TABLE WAITING (
    WAITING_ID BIGINT AUTO_INCREMENT COMMENT '대기열 ID',
    USER_ID BIGINT NOT NULL COMMENT '회원 ID',
    CONCERT_ID BIGINT NOT NULL COMMENT '콘서트 ID',
    TOKEN VARCHAR(255) NOT NULL COMMENT '토큰',
    STATUS VARCHAR(10) DEFAULT 'WAIT' COMMENT '상태', -- WAIT, ACTIVE, DELETE
    CREATED_AT DATETIME DEFAULT NOW() COMMENT '생성일',
    UPDATED_AT DATETIME NULL COMMENT '수정일',
    DELETED_AT DATETIME NULL COMMENT '삭제일',
    PRIMARY KEY (WAITING_ID)
) COMMENT '대기열';
